### ISSUE TITLE
Multiple viewports and cameras

### ISSUE THREAD

**Issue by encelo** [nCine/nCine#16]
The main rationale behind supporting viewports is the possibility of having off-screen render targets, a feature that can be used together with custom shaders (#2) to allow for post-processing effects like bloom, depth of field or normal mapping illumination.

An off-screen render target might also be used to scale the game output to a custom resolution that is different than the screen one (it could be a workaround for Android fixed resolution, for example).

The viewport will also allow the use of a dedicated camera class that should alleviate the need for a dummy node to simulate camera transformations like in the current version of `apptest_camera`.
The camera class will use uniform variables to send data to nodes: projection and view matrices will be multiplied inside the vertex shader.

By also adding a "dirty flag" for scene node transformations it will be possible to move nodes with the camera without recalculating their scenegraph transformations, thus saving a lot of precious CPU time. Screen culling code should also be updated to work with viewports and cameras.

## TO-DO
- [x] Move clear color and OpenGL viewport methods of the `IGfxDevice` class in the `Viewport` one
  - [x] Fix compilation of external projects (`ncParticleEditor`, `ncJugiMapGuiDemo`, etc...)
  - [x] Use the new camera in the `ncTiledViewer` project
 - [x] Have viewports with a camera but no texture, in order to add more transformation flexibility
   - [x] Add the option to use a texture-less viewport with a camera class in `apptest_camera`
- [x] Fix screen culling within a viewport (maybe with some form of spatial hashing?)
- [x] Add dirty flags to avoid unneeded scene node transformations and AABB box recalculations
- [x] Replicate the new class and methods in the Lua API

#### Godot
- [Camera class (Godot reference)](https://docs.godotengine.org/en/stable/classes/class_camera.html)
- [Viewport class (Godot reference)](https://docs.godotengine.org/en/stable/classes/class_viewport.html)
- [Using Viewports (Godot tutorial)](https://docs.godotengine.org/en/stable/tutorials/viewports/viewports.html)
- [Custom post-processing (Godot tutorial)](https://docs.godotengine.org/en/stable/tutorials/viewports/custom_postprocessing.html)

#### Ogre
- [Viewport class (Ogre reference)](https://www.ogre3d.org/docs/api/1.8/class_ogre_1_1_viewport.html)
- [RenderTarget class (Ogre reference)](https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_render_target.html)
- [Multiple and Dual SceneManagers (Ogre tutorial)](http://wiki.ogre3d.org/Basic+Tutorial+8)
- [Render to Texture (Ogre tutorial)](https://wiki.ogre3d.org/Intermediate+Tutorial+7)

#### Other
- [Choosing the resolution of your 2D art assets (Unity article)](https://blogs.unity3d.com/2018/11/19/choosing-the-resolution-of-your-2d-art-assets/)
- [Post-Processing Effects in Cocos2d-x](https://www.babaei.net/blog/post-processing-effects-in-cocos2d-x/)
- [Architecture of Lugdunum](https://lugdunum3d.github.io/doc/architecture.html)
- [Fast Extraction of Viewing Frustum Planes from the WorldView-Projection Matrix (PDF)](https://www.gamedevs.org/uploads/fast-extraction-viewing-frustum-planes-from-world-view-projection-matrix.pdf)
