### ISSUE TITLE
Custom Shaders

### ISSUE THREAD

**Issue by encelo** [nCine/nCine#2]
It has been a long time now since I first thought about the possibility to provide a way for users to override the default shaders.

The task has been delayed for a long time because I had other priorities and because I thought I needed to refactor (yes, again) the rendering system before trying to add this interesting but possibly complex feature.

As both [Jugilus](https://github.com/Jugilus) and the team behind the [deadfish](https://github.com/capturcus/deadfish) game recently asked for this I decided to shuffle it higher in my priority list. :wink:

Don't hesitate to comment on this issue or on our [Discord server](https://discord.gg/495ab6Y)! :speech_balloon: 

## TO-DO
- [x] Create a class abstracting the shader state of a `DrawableNode`
- [x] Shader reloading and recompilation should be fault tolerant (like other resources in #3)
- [x] Should the `Shader` class derive from `Object`?
  - What are the implications of this choice? :thinking: 
- [x] Provide a way for the user to decide how matrices are passed
  - Like the name of the model view matrix uniform and if it is in a named block or not
- [x] Provide a way for the user to link the semantics to an attribute name
  - "_`aPosition` contains vertex positions_"
- [x] Proper handling of shader loading and compilation errors
  - Should the application exit? Can the shader be reloaded? :thinking:
- [x] Find a way not to sacrifice batching for nodes with custom shaders
- [x] Should there be always available uniforms and attributes with default names or all data driven?
- [x] Proper testing with all drawable node types
- [x] Test on Android and Emscripten, test `glapptest_fbo_cube`
- [x] When loading custom shaders it should be possible to use default for certain stages
  - For example use the default `Sprite` vertex shader and only provide a custom fragment one
- [x] Add a corresponding Lua API for custom shaders
- [x] Before merging or rebasing: run `clang-format` and check compilation of all commits, write the [master branch](https://ncine.github.io/download-master/) changelog, update the [features](https://ncine.github.io/features/) section, and add `apptest_shaders` to the [web-tests](https://ncine.github.io/web-tests/), then delete the remote branch.
- [x] Check if the rest of the projects compile with the changes from this branch (for example `ncTiledViewer` does not)

### References
- SFML: [Adding special effects with shaders](https://www.sfml-dev.org/tutorials/2.0/graphics-shader.php)
- Cocos2d-x: [Shaders and Materials](https://docs.cocos2d-x.org/cocos2d-x/v3/en/advanced_topics/shaders.html)
- Cocos2D: [How To Create Cool Effects with Custom Shaders in OpenGL ES 2.0 and Cocos2D 2.X](https://www.raywenderlich.com/2941-how-to-create-cool-effects-with-custom-shaders-in-opengl-es-2-0-and-cocos2d-2-x)
- AppGameKit: [Shaders in AGK](https://www.appgamekit.com/documentation/guides/13_shaders.htm)
- PlayCanvas: [Custom Shaders](https://developer.playcanvas.com/en/tutorials/custom-shaders/)
- XNA4: [XNA 4 tutorial: Custom shader Effects](https://www.andrejeworutzki.de/game-developement/xna-4-tutorial-custom-shader-effects/)
- [5 Simple Fragment Shaders for 2D Games (GLSL)](http://ninslash.com/5-simple-fragment-shaders-for-2d-games-glsl/)
- [Fast Gaussian Blur with Cocos2d-x](https://stackoverflow.com/questions/46745199/fast-gaussian-blur-at-pause/46862300)
- [Multi-pass technique in Ogre 3D](https://www.ogre3d.org/docs/manual18/manual_74.html)
- https://www.gdcvault.com/play/1021762/Advanced-Visual-Effects-for-2D
- [Graveyard Keeper: How the graphics effects are made](https://www.gamedeveloper.com/programming/graveyard-keeper-how-the-graphics-effects-are-made)
