### ISSUE TITLE
Resource reloading and fault tolerance

### ISSUE THREAD

**Issue by encelo** [nCine/nCine#3]
I'm working on some changes in resource loading in order to support a typical GUI tool workflow, think of an editor. :wink:

You should be able to load a resource, say a texture, from a file, then assign it to a bunch of sprites and then change the texture by loading a second file and have all your sprites automatically update.

Recently I have committed some changes to enhance the fault tolerance of loading a resource by providing an optional class that wraps the data being loaded and that can be queried to see if the process has been successful.

I'm thinking about changing the approach, delete the data classes and unify the reload and the fault tolerance API.

This way you will be able to create an empty texture and load it with data at a later time. You will be able to load data from texels in memory (making it possible to have CPU procedural generated textures), or from a file. You will be able to load a new file to the same texture and if the loading process fails the texture will be left unchanged.

I should also create a new `apptest_loading` that shows how to load resources (from file, from a memory file, from a memory buffer) and how to reload them.

### The feature branch
- `new_loading` -> **The branch has been merged to `master`**

As a starting point I suggest you have a look at the new [apptest_loading](https://github.com/nCine/nCine/blob/master/tests/apptest_loading.cpp).

## TO-DO
- [x] Add an empty `Texture::Texture()` constructor that only creates the OpenGL texture name (`glGenTextures`)
- [x] Add an empty `Font::Font()` constructor and check `AudioBuffer::AudioBuffer()`
- [x] In `apptest_loading` test changing a texture and an audio buffer format by assigning a new object
- [X] In `apptest_loading` add a section to load sounds and fonts from memory and file
- [x] In `apptest_loading` check the fault tolerance by trying loading non existing files or files and memory buffers with random data
- [x] Check how feasible is to reload in the case of `AudioStream` (and add `AudioStream::AudioStream()`)
- [x] Study how to integrate OpenAL `AL_*_OFFSET` source properties for sound buffer or stream seeking
- [x] Update `apptest_audio` to use the new `ncine-data/sounds` files (and add the display of audio offsets)
- [x] Remove any `FATAL_ASSERT` while loading or creating resources
- [X] Rewrite the `Texture/Audio/FontData` commit to split some changes from the `new_loading` one
- [x] Before merging or rebasing run `clang-format`, write the [master branch](https://ncine.github.io/download-master/) changelog and add `apptest_loading` to the [web-tests](https://ncine.github.io/web-tests/)

**Comment by encelo** [comment]
I have merged the `new_loading` branch to `master`.
